module Factorix
  class CLI
    module Commands
      module MOD
        module Settings
          class Dump < Dry::CLI::Command
            def call: (?settings_file: String?, ?output: String?, **untyped) -> void
          end
        end
      end
    end
  end
end
