AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  EnabledByDefault: true
  Exclude:
    - bin/**/*
    - vendor/**/*
    - factorix.old/**/*
  ExtraDetails: true
  NewCops: enable
  TargetRubyVersion: 3.2
  UseCache: true

inherit_mode:
  merge:
    - Exclude

plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

inherit_gem:
  docquet:
    - config/cops/bundler.yml
    - config/cops/gemspec.yml
    - config/cops/layout.yml
    - config/cops/lint.yml
    - config/cops/metrics.yml
    - config/cops/naming.yml
    - config/cops/performance.yml
    - config/cops/rake.yml
    - config/cops/rspec.yml
    - config/cops/security.yml
    - config/cops/style.yml

inherit_from: .rubocop_todo.yml

# Project-specific settings
Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Exclude:
    - lib/factorix/types/mod_info.rb

Naming/PredicateMethod:
  Exclude:
    - lib/factorix/cache/file_system.rb
    - lib/factorix/ser_des/deserializer.rb

Naming/VariableNumber:
  Exclude:
    - spec/factorix/ser_des/deserializer_spec.rb
    - spec/factorix/types/game_version_spec.rb
    - spec/factorix/types/mod_version_spec.rb

RSpec/ExampleLength:
  Enabled: false

RSpec/IndexedLet:
  Exclude:
    - spec/factorix/types/game_version_spec.rb
    - spec/factorix/types/mod_version_spec.rb

RSpec/RepeatedExampleGroupBody:
  Exclude:
    - spec/factorix/ser_des/deserializer_spec.rb

Style/IpAddresses:
  Exclude:
    - spec/factorix/types/game_version_spec.rb
    - spec/factorix/types/mod_version_spec.rb