---
AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  EnabledByDefault: true
  Exclude:
  - bin/**/*
  - vendor/**/*
  ExtraDetails: true
  TargetRubyVersion: 3.4
  UseCache: true
inherit_mode:
  merge:
  - AllowedCops
  - Exclude
plugins:
- rubocop-performance
- rubocop-rake
- rubocop-rspec
- rubocop-thread_safety
require: []
inherit_from:
  - .rubocop_todo.yml
  - .rubocop/bundler.yml
  - .rubocop/gemspec.yml
  - .rubocop/layout.yml
  - .rubocop/lint.yml
  - .rubocop/metrics.yml
  - .rubocop/migration.yml
  - .rubocop/naming.yml
  - .rubocop/performance.yml
  - .rubocop/rspec.yml
  - .rubocop/rake.yml
  - .rubocop/security.yml
  - .rubocop/style.yml
  - .rubocop/threadsafety.yml

# These serializer/deserializer classes handle complex binary data formats
# and require complex logic that cannot be easily simplified without
# compromising readability and maintainability.
Metrics/AbcSize:
  Exclude:
    - 'lib/factorix/deserializer.rb'
    - 'lib/factorix/serializer.rb'

# The deserializer and serializer classes need to handle multiple data types
# and format variations, requiring conditional logic that naturally increases
# cyclomatic complexity.
Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/factorix/deserializer.rb'
    - 'lib/factorix/serializer.rb'

# These methods implement core serialization/deserialization logic that
# needs to handle multiple cases in a cohesive way. Breaking them up would
# reduce readability and make the code harder to maintain.
Metrics/MethodLength:
  Exclude:
    - 'lib/factorix/deserializer.rb'
    - 'lib/factorix/serializer.rb'

# The serializer class needs to handle many different data types and formats,
# which naturally leads to a larger class with more methods.
Metrics/ClassLength:
  Exclude:
    - 'lib/factorix/serializer.rb'
