AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  EnabledByDefault: true
  Exclude:
    - bin/**/*
    - vendor/**/*
    - factorix.old/**/*
    - example/**/*
  ExtraDetails: true
  NewCops: enable
  TargetRubyVersion: 3.2
  UseCache: true

inherit_mode:
  merge:
    - Exclude

plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

inherit_gem:
  docquet:
    - config/cops/bundler.yml
    - config/cops/gemspec.yml
    - config/cops/layout.yml
    - config/cops/lint.yml
    - config/cops/metrics.yml
    - config/cops/naming.yml
    - config/cops/performance.yml
    - config/cops/rake.yml
    - config/cops/rspec.yml
    - config/cops/security.yml
    - config/cops/style.yml
    - config/cops/thread_safety.yml

inherit_from: .rubocop_todo.yml

Naming/PredicateMethod:
  Exclude:
    - lib/factorix/cache/file_system.rb # fetch/store/delete return boolean but are standard cache API names
    - lib/factorix/ser_des/deserializer.rb # read_bool follows binary deserialization naming convention

Naming/VariableNumber:
  AllowedPatterns:
    - '^version_\d+'        # Allow version_1_0_0, version_123, etc.
    - '_v\d+$'              # Allow mod1_v1, etc.
    - '^requirement_\w+_\d+' # Allow requirement_ge_1_2_0, etc.

RSpec/IndexedLet:
  AllowedPatterns:
    - '^version_\d+'  # Allow version_1_0_0, version_123, etc.
    - '^edge\d+$'     # Allow edge1, edge2, etc.
    - '^mod\d+_v\d+$' # Allow mod1_v1, mod2_v1, etc.
    - '^node\d+$'     # Allow node1, node2, etc.
    - '^error\d+$'    # Allow error1, error2, etc.
    - '^suggestion\d+$' # Allow suggestion1, suggestion2, etc.

Style/IpAddresses:
  Exclude:
    - spec/factorix/game_version_spec.rb
    - spec/factorix/mod_version_spec.rb

Style/StaticClass:
  Exclude:
    - lib/factorix/info_json.rb

ThreadSafety/NewThread:
  Exclude:
    - spec/factorix/runtime/wsl/wsl_path_spec.rb
