AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  EnabledByDefault: true
  Exclude:
    - bin/**/*
    - vendor/**/*
    - factorix.old/**/*
    - example/**/*
  ExtraDetails: true
  NewCops: enable
  TargetRubyVersion: 3.2
  UseCache: true

inherit_mode:
  merge:
    - Exclude

plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

inherit_gem:
  docquet:
    - config/cops/bundler.yml
    - config/cops/gemspec.yml
    - config/cops/layout.yml
    - config/cops/lint.yml
    - config/cops/metrics.yml
    - config/cops/naming.yml
    - config/cops/performance.yml
    - config/cops/rake.yml
    - config/cops/rspec.yml
    - config/cops/security.yml
    - config/cops/style.yml
    - config/cops/thread_safety.yml

inherit_from: .rubocop_todo.yml

# Project-specific settings
Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - lib/factorix/dependency/resolver.rb

Metrics/PerceivedComplexity:
  Exclude:
    - lib/factorix/types/mod_info.rb
    - lib/factorix/dependency/parser.rb
    - lib/factorix/dependency/list.rb
    - lib/factorix/dependency/resolver.rb
    - lib/factorix/cli/commands/mod/edit.rb
    - lib/factorix/installed_mod.rb
    - lib/factorix/cli/commands/mod/enable.rb
    - lib/factorix/cli/commands/mod/uninstall.rb

Metrics/ParameterLists:
  Exclude:
    - lib/factorix/cli/commands/mod/enable.rb

Naming/PredicateMethod:
  Exclude:
    - lib/factorix/cache/file_system.rb
    - lib/factorix/ser_des/deserializer.rb

Naming/VariableNumber:
  AllowedPatterns:
    - '^version_\d+'        # Allow version_1_0_0, version_123, etc.
    - '_v\d+$'              # Allow mod1_v1, etc.
    - '^requirement_\w+_\d+' # Allow requirement_ge_1_2_0, etc.

RSpec/ExampleLength:
  Enabled: false

RSpec/IndexedLet:
  AllowedPatterns:
    - '^version_\d+'  # Allow version_1_0_0, version_123, etc.
    - '^edge\d+$'     # Allow edge1, edge2, etc.
    - '^mod\d+_v\d+$' # Allow mod1_v1, mod2_v1, etc.
    - '^node\d+$'     # Allow node1, node2, etc.
    - '^error\d+$'    # Allow error1, error2, etc.
    - '^suggestion\d+$' # Allow suggestion1, suggestion2, etc.

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/RepeatedExampleGroupBody:
  Exclude:
    - spec/factorix/ser_des/deserializer_spec.rb

RSpec/SubjectStub:
  Exclude:
    - spec/factorix/cli/commands/launch_spec.rb

Style/IpAddresses:
  Exclude:
    - spec/factorix/types/game_version_spec.rb
    - spec/factorix/types/mod_version_spec.rb