module Factorix
  module Types
    class Category
      attr_reader value: String
      attr_reader name: String
      attr_reader description: String

      def self.for: (String value) -> Category
    end
  end
end
