module Factorix
  module Types
    class GameVersion
      include Comparable

      attr_reader major: Integer
      attr_reader minor: Integer
      attr_reader patch: Integer
      attr_reader build: Integer

      def self.from_string: (String str) -> GameVersion

      def self.from_numbers: (Integer major, Integer minor, Integer patch, ?Integer build) -> GameVersion

      def to_s: () -> String

      def to_a: () -> Array[Integer]

      def <=>: (GameVersion other) -> Integer?

      private

      def initialize: (major: Integer, minor: Integer, patch: Integer, build: Integer) -> void
    end
  end
end
