module Factorix
  module Types
    class MODListEntry
      attr_reader name: String
      attr_reader title: String
      attr_reader owner: String
      attr_reader summary: String
      attr_reader downloads_count: Integer
      attr_reader category: Category
      attr_reader score: Float
      attr_reader latest_release: Release?
      attr_reader releases: Array[Release]?

      def initialize: (
        name: String,
        title: String,
        owner: String,
        summary: String,
        downloads_count: Integer,
        category: String,
        score: Float,
        ?latest_release: Hash[String, untyped]?,
        ?releases: Array[Hash[String, untyped]]?
      ) -> void
    end
  end
end
