module Factorix
  module Types
    class Tag
      attr_reader value: String
      attr_reader name: String
      attr_reader description: String

      def self.for: (String value) -> Tag

      private

      def self.new: (value: String, name: String, description: String) -> Tag
      def self.[]: (value: String, name: String, description: String) -> Tag
    end
  end
end
