# RBS type signature file
# NOTE: Do not include private method definitions in RBS files.
#       Only public interfaces should be documented here.

module Dry
  module AutoInject
    interface _Builder
      def []: (*String dependencies) -> Module
    end

    def self.new: (untyped container) -> _Builder
  end

  def self.AutoInject: (untyped container) -> AutoInject::_Builder
end
