module Factorix
  module Transfer
    class Downloader
      attr_reader logger: Dry::Logger::Dispatcher
      attr_reader cache: Cache::FileSystem
      attr_reader client: HTTP::Client

      def download: (URI::HTTPS url, Pathname output) -> void
    end
  end
end
