module Factorix
  module Progress
    class Presenter
      def initialize: (?title: String, ?output: IO) -> void

      def start: (total: Integer, ?format: String?) -> void

      def update: (Integer current) -> void

      def finish: () -> void
    end
  end
end
