# RBS type signature file
# NOTE: Do not include private method definitions in RBS files.
#       Only public interfaces should be documented here.

module Factorix
  module API
    class License
      attr_reader id: String
      attr_reader name: String
      attr_reader title: String
      attr_reader description: String
      attr_reader url: URI::HTTPS

      def initialize: (id: String, name: String, title: String, description: String, url: String) -> void
    end
  end
end
