module Factorix
  module API
    class MODDownloadAPI
      BASE_URL: String

      attr_reader downloader: Transfer::Downloader
      attr_reader logger: Dry::Logger::Dispatcher

      def initialize: (**untyped deps) -> void

      def download: (String download_url, Pathname output) -> void
    end
  end
end
