# RBS type signature file
# NOTE: Do not include private method definitions in RBS files.
#       Only public interfaces should be documented here.

module Factorix
  module API
    class MODPortalAPI
      BASE_URL: String

      attr_reader logger: Dry::Logger::Dispatcher
      attr_reader cache: Cache::FileSystem
      attr_reader client: HTTP::Client

      def get_mods: (
                      *String namelist,
                      ?hide_deprecated: bool?,
                      ?page: Integer?,
                      ?page_size: (Integer | String)?,
                      ?sort: ("name" | "created_at" | "updated_at")?,
                      ?sort_order: ("asc" | "desc")?,
                      ?version: ("0.13" | "0.14" | "0.15" | "0.16" | "0.17" | "0.18" | "1.0" | "1.1" | "2.0")?
                    ) -> Hash[String, untyped]

      def get_mod: (String name) -> Hash[String, untyped]

      def get_mod_full: (String name) -> Hash[String, untyped]
    end
  end
end
