# RBS type signature file
# NOTE: Do not include private method definitions in RBS files.
#       Only public interfaces should be documented here.

module Factorix
  module API
    class Release
      attr_reader download_url: URI::HTTPS
      attr_reader file_name: String
      attr_reader info_json: Hash[String, untyped]
      attr_reader released_at: Time
      attr_reader version: MODVersion
      attr_reader sha1: String
      attr_reader feature_flags: Array[String]

      def initialize: (
        download_url: String,
        file_name: String,
        info_json: Hash[String, untyped],
        released_at: String,
        version: String,
        sha1: String,
        ?feature_flags: Array[String]
      ) -> void
    end
  end
end
