module Factorix
  class Runtime
    class Base
      def user_dir: () -> Pathname

      def mods_dir: () -> Pathname

      def mod_list_path: () -> Pathname

      def mod_settings_path: () -> Pathname

      def player_data_path: () -> Pathname

      def xdg_cache_home_dir: () -> Pathname

      def xdg_config_home_dir: () -> Pathname

      def xdg_data_home_dir: () -> Pathname

      def factorix_cache_dir: () -> Pathname

      def factorix_config_path: () -> Pathname
    end
  end
end
