module Factorix
  class Runtime
    class Windows < Base
      def initialize: (?path: WindowsPath) -> void

      def user_dir: () -> Pathname

      class WindowsPath
        def app_data: () -> Pathname

        def local_app_data: () -> Pathname
      end
    end
  end
end
