module Factorix
  class Runtime
    # WSL runtime environment
    class WSL < Windows
      # WSL specific path handling
      class WSLPath
        extend Dry::Core::Cache

        # Return the path to the user's AppData directory
        # @return [Pathname] path to the user's AppData directory
        def app_data: () -> Pathname

        # Return the path to the Program Files (x86) directory
        # @return [Pathname] path to the Program Files (x86) directory
        def program_files_x86: () -> Pathname

        private

        def cmd_echo: (String name) -> String
        def wslvar: (String name) -> String
        def wslpath: (String path) -> String
      end

      # Initialize WSL runtime environment
      def initialize: (?path: WSLPath) -> void

      private

      attr_reader path: WSLPath

      public

      # Check if the game is running
      # @return [Boolean] true if the game is running, false otherwise
      def running?: () -> bool
    end
  end
end
