module Factorix
  class Runtime
    class WSL < Windows
      def initialize: (?path: WSLPath) -> void

      class WSLPath
        def app_data: () -> Pathname

        def local_app_data: () -> Pathname
      end
    end
  end
end
