module Factorix
  class CLI
    module Commands
      module Mod
        # Command for disabling a mod
        class Disable < Dry::CLI::Command
          # Disable a MOD
          # @param mod [String] The MOD to disable
          # @param options [Hash] The options for the command
          # @option options [Boolean] :verbose Print more information
          def call: (mod: String, **untyped options) -> void
        end
      end
    end
  end
end
