module Factorix
  class CLI
    module Commands
      module MOD
        class Download < Dry::CLI::Command
          class ProgressHandler
            def initialize: (Progress::MultiBar multi_bar, String mod_name, String file_name) -> void

            def on_download_started: (untyped event) -> void

            def on_download_progress: (untyped event) -> void

            def on_download_completed: (untyped _event) -> void
          end

          @portal: Portal
          @http: Transfer::HTTP

          def call: (mod_specs: Array[String], ?directory: String, ?jobs: Integer) -> void
        end
      end
    end
  end
end
