module Factorix
  class CLI
    module Commands
      module MOD
        class Download < Dry::CLI::Command
          @portal: Portal
          @http: Transfer::HTTP

          def call: (mod_specs: Array[String], ?directory: String, ?jobs: Integer) -> void
        end
      end
    end
  end
end
