module Factorix
  module SerDes
    class Deserializer
      def initialize: (untyped stream) -> void

      def read_bytes: (Integer length) -> String

      def read_u8: () -> Integer

      def read_u16: () -> Integer

      def read_u32: () -> Integer

      def read_optim_u16: () -> Integer

      def read_optim_u32: () -> Integer

      def read_u16_tuple: (Integer length) -> Array[Integer]

      def read_bool: () -> bool

      def read_str: () -> String

      def read_str_property: () -> String

      def read_double: () -> Float

      def read_game_version: () -> GameVersion

      def read_mod_version: () -> MODVersion

      def read_long: () -> Integer

      def read_unsigned_long: () -> Integer

      def read_dictionary: () -> Hash[String, untyped]

      def read_list: () -> Hash[String, untyped]

      def read_property_tree: () -> (nil | bool | Float | String | Array[untyped] | Hash[String, untyped] | Integer)

      def eof?: () -> bool
    end
  end
end
