module Factorix
  module SerDes
    class GameVersion
      include Comparable

      def initialize: (String version_string) -> void
                    | (Integer major, Integer minor, Integer patch, Integer build) -> void

      def self.[]: (String version_string) -> GameVersion
                 | (Integer major, Integer minor, Integer patch, Integer build) -> GameVersion

      def to_s: () -> String

      def to_a: () -> Array[Integer]

      def <=>: (GameVersion other) -> Integer?
    end
  end
end
