module Factorix
  module SerDes
    class MODVersion
      include Comparable

      def initialize: (String version_string) -> void
                    | (Integer major, Integer minor, Integer patch) -> void

      def self.[]: (String version_string) -> MODVersion
                 | (Integer major, Integer minor, Integer patch) -> MODVersion

      def to_s: () -> String

      def to_a: () -> Array[Integer]

      def <=>: (MODVersion other) -> Integer?
    end
  end
end
