module Factorix
  module SerDes
    class Serializer
      def initialize: (untyped stream) -> void

      def write_bytes: (String data) -> void

      def write_u8: (Integer uint8) -> void

      def write_u16: (Integer uint16) -> void

      def write_u32: (Integer uint32) -> void

      def write_optim_u16: (Integer uint16) -> void

      def write_optim_u32: (Integer uint32) -> void

      def write_bool: (bool bool) -> void

      def write_str: (String str) -> void

      def write_str_property: (String str) -> void

      def write_double: (Float dbl) -> void

      def write_game_version: (GameVersion game_version) -> void

      def write_mod_version: (MODVersion mod_version) -> void

      def write_list: (Array[untyped] list) -> void

      def write_dictionary: (Hash[String, untyped] dict) -> void

      def write_long: (Integer long) -> void

      def write_unsigned_long: (Integer ulong) -> void

      def write_property_tree: (nil | bool | Float | String | Array[untyped] | Hash[String, untyped] | Integer obj) -> void
    end
  end
end
