# RBS type signature file
# NOTE: Do not include private method definitions in RBS files.
#       Only public interfaces should be documented here.

module Dry
  module Core
    module Container
      module Mixin
        def register: (Symbol | String, ?memoize: bool) ?{ () -> untyped } -> void

        def resolve: (Symbol | String) -> untyped

        def []: (Symbol | String) -> untyped
      end
    end
  end
end
