module Factorix
  class Application
    extend Dry::Container::Mixin
    extend Dry::Configurable

    def self.register: (Symbol, ?memoize: bool) { () -> untyped } -> void

    def self.resolve: (Symbol) -> untyped

    def self.[]: (Symbol) -> untyped

    def self.config: () -> Config

    def self.configure: () { (Config) -> void } -> void

    def self.load_config: (?String? path) -> void

    class Config
      def log_level: () -> Symbol

      def log_level=: (Symbol) -> void

      def http: () -> HttpConfig

      def cache: () -> CacheConfig
    end

    class HttpConfig
      def connect_timeout: () -> Integer

      def connect_timeout=: (Integer) -> void

      def read_timeout: () -> Integer

      def read_timeout=: (Integer) -> void

      def write_timeout: () -> Integer

      def write_timeout=: (Integer) -> void
    end

    class CacheConfig
      def download: () -> CacheInstanceConfig

      def api: () -> CacheInstanceConfig
    end

    class CacheInstanceConfig
      def dir: () -> Pathname

      def dir=: (Pathname | String) -> void

      def ttl: () -> Integer?

      def ttl=: (Integer?) -> void

      def max_file_size: () -> Integer?

      def max_file_size=: (Integer?) -> void
    end
  end
end
