module Factorix
  # Command-line interface for Factorix
  class CLI
    extend Dry::CLI::Registry

    # Register the info command
    def self.register: (String, singleton(Factorix::CLI::Commands::Info)) -> void

    # Register the launch command
    def self.register: (String, singleton(Factorix::CLI::Commands::Launch)) -> void

    # Register the mod disable command
    def self.register: (String, singleton(Factorix::CLI::Commands::Mod::Disable)) -> void

    # Register the mod enable command
    def self.register: (String, singleton(Factorix::CLI::Commands::Mod::Enable)) -> void

    # Register the mod list command
    def self.register: (String, singleton(Factorix::CLI::Commands::Mod::List)) -> void
  end
end
