# RBS type signature file
# NOTE: Do not include private method definitions in RBS files.
#       Only public interfaces should be documented here.

module Factorix
  class Container
    extend Dry::Core::Container::Mixin

    def self.register: (Symbol, ?memoize: bool) { () -> untyped } -> void

    def self.resolve: (Symbol) -> untyped

    def self.[]: (Symbol) -> untyped
  end
end
