module Factorix
  # Manages Factorio service credentials
  class Credential
    # Return the service username
    # @return [String] the service username
    def username: () -> String

    # Return the service token
    # @return [String] the service token
    def token: () -> String

    private

    def runtime: () -> Runtime

    def player_data: () -> Hash[String, String]
  end
end
