# RBS type signature file
# NOTE: Do not include private method definitions in RBS files.
#       Only public interfaces should be documented here.

module Factorix
  class InstalledMOD
    include Comparable

    ZIP_FORM: Symbol

    DIRECTORY_FORM: Symbol

    def self.scan: (Pathname mod_dir) -> Array[InstalledMOD]

    def self.find_by_name: (Pathname mod_dir, String name) -> Array[InstalledMOD]

    def self.find: (Pathname mod_dir, String name, ?Types::MODVersion? version) -> InstalledMOD?

    def initialize: (mod: MOD, version: Types::MODVersion, form: Symbol, path: Pathname, info: Types::InfoJSON) -> void

    attr_reader mod: MOD

    attr_reader version: Types::MODVersion

    attr_reader form: Symbol

    attr_reader path: Pathname

    attr_reader info: Types::InfoJSON

    def <=>: (InstalledMOD other) -> Integer?
  end
end
