# RBS type signature file
# NOTE: Do not include private method definitions in RBS files.
#       Only public interfaces should be documented here.

module Factorix
  # Represents a local MOD
  class MOD < Data
    include Comparable

    attr_reader name: String

    def base?: () -> bool

    def expansion?: () -> bool

    def to_s: () -> String

    def <=>: (untyped other) -> Integer?
  end
end
