# RBS type signature file
# NOTE: Do not include private method definitions in RBS files.
#       Only public interfaces should be documented here.

module Factorix
  class MODVersion
    include Comparable

    attr_reader major: Integer
    attr_reader minor: Integer
    attr_reader patch: Integer

    def self.from_string: (String str) -> MODVersion

    def self.from_numbers: (Integer major, Integer minor, Integer patch) -> MODVersion

    def to_s: () -> String

    def to_a: () -> Array[Integer]

    def <=>: (MODVersion other) -> Integer?
  end
end
