# RBS type signature file
# NOTE: Do not include private method definitions in RBS files.
#       Only public interfaces should be documented here.

module Factorix
  # Represents a list of MODs and their enabled status
  class MODList
    include Enumerable[[MOD, MODState]]

    # Raised when a MOD is not found in the list
    class MODNotInListError < Factorix::MODNotFoundError
    end

    @mods: Hash[MOD, MODState]

    def self.load: (?Pathname path) -> MODList

    def initialize: (?Hash[MOD, MODState] mods) -> void

    def save: (?Pathname path) -> void

    def each: () -> Enumerator[[MOD, MODState], self]
            | () { ([MOD, MODState]) -> void } -> self

    def each_mod: () -> Enumerator[MOD, self]
                | () { (MOD) -> void } -> self

    alias each_key each_mod

    def add: (MOD mod, ?enabled: bool, ?version: MODVersion?) -> void

    def remove: (MOD mod) -> void

    def exist?: (MOD mod) -> bool

    def enabled?: (MOD mod) -> bool

    def version: (MOD mod) -> MODVersion?

    def enable: (MOD mod) -> void

    def disable: (MOD mod) -> void
  end
end
