module Factorix
  # Manages temporary MOD configurations
  class ModContext
    # @param mod_list [Factorix::ModList] the MOD list
    def initialize: (ModList mod_list) -> void

    # Execute a block with only specified MODs enabled
    # @param mod_names [Array<String>] the names of the MODs to enable
    def with_only_enabled: (*String mod_names) { () -> void } -> void

    private

    attr_reader mod_list: ModList
    attr_reader original_states: Hash[Mod, bool]

    def save_original_states: () -> void
    def enable_only_specified: (*String mod_names) -> void
    def restore_original_states: () -> void
  end
end
