module Factorix
  class MODInstallationState
    @mod_list: MODList?
    @installed_mods: Array[InstalledMOD]?
    @graph: Dependency::Graph?

    def mod_list: () -> MODList
    def installed_mods: () -> Array[InstalledMOD]
    def graph: () -> Dependency::Graph
  end
end
