module Factorix
  class MODDependency
    REQUIRED: Symbol
    OPTIONAL: Symbol
    HIDDEN_OPTIONAL: Symbol
    INCOMPATIBLE: Symbol
    LOAD_NEUTRAL: Symbol

    attr_reader mod: MOD
    attr_reader type: Symbol
    attr_reader version_requirement: Types::MODVersionRequirement?

    def initialize: (mod: MOD, type: Symbol, ?version_requirement: Types::MODVersionRequirement?) -> void

    def required?: () -> bool
    def optional?: () -> bool
    def incompatible?: () -> bool
    def load_neutral?: () -> bool

    def satisfied_by?: (Types::MODVersion version) -> bool

    def to_s: () -> String
  end
end
