# RBS type signature file
# NOTE: Do not include private method definitions in RBS files.
#       Only public interfaces should be documented here.

module Factorix
  class Portal
    def list_mods: (
                     *String namelist,
                     ?hide_deprecated: bool?,
                     ?page: Integer?,
                     ?page_size: (Integer | String)?,
                     ?sort: ("name" | "created_at" | "updated_at")?,
                     ?sort_order: ("asc" | "desc")?,
                     ?version: ("0.13" | "0.14" | "0.15" | "0.16" | "0.17" | "0.18" | "1.0" | "1.1" | "2.0")?
                   ) -> Array[Types::MODInfo]

    def get_mod: (String name) -> Types::MODInfo

    def get_mod_full: (String name) -> Types::MODInfo

    def download_mod: (Types::Release release, Pathname output) -> void

    def upload_mod: (String mod_name, Pathname file_path, **untyped metadata) -> void

    def edit_mod: (String mod_name, **untyped metadata) -> void

    def add_mod_image: (String mod_name, Pathname image_file) -> Types::Image

    def edit_mod_images: (String mod_name, Array[String] image_ids) -> void

    attr_reader mod_portal_api: API::MODPortalAPI

    attr_reader mod_download_api: API::MODDownloadAPI

    attr_reader mod_management_api: API::MODManagementAPI
  end
end
