module Factorix
  class Portal
    def list_mods: (
                     *String namelist,
                     ?hide_deprecated: bool?,
                     ?page: Integer?,
                     ?page_size: (Integer | String)?,
                     ?sort: ("name" | "created_at" | "updated_at")?,
                     ?sort_order: ("asc" | "desc")?,
                     ?version: ("0.13" | "0.14" | "0.15" | "0.16" | "0.17" | "0.18" | "1.0" | "1.1" | "2.0")?
                   ) -> Array[Types::MODInfo]

    def get_mod: (String name) -> Types::MODInfo

    def get_mod_full: (String name) -> Types::MODInfo

    def download_mod: (Types::Release release, Pathname | String output) -> void

    attr_reader mod_list_api: API::MODListAPI

    attr_reader mod_download_api: API::MODDownloadAPI
  end
end
