module Factorix
  class ServiceCredential
    def self.from_env: () -> ServiceCredential

    def self.from_player_data: (runtime: Runtime::Base) -> ServiceCredential

    def username: () -> String

    def token: () -> String
  end
end
