module Factorix
  class MODSettings
    class CSVConverter
      def convert_to: (MODSettings settings) -> String

      def convert_from: (String csv_string) -> MODSettings

      private

      def convert_value_for_output: (untyped value) -> untyped
    end
  end
end
