module Factorix
  class MODSettings
    class TOMLConverter
      def convert_to: (MODSettings settings) -> String

      def convert_from: (String toml_string) -> MODSettings

      private

      def build_hash: (MODSettings settings) -> Hash[String, untyped]

      def convert_value_for_output: (untyped value) -> untyped

      def build_settings: (Hash[String, untyped] data) -> MODSettings

      def convert_value_for_input: (untyped value) -> untyped
    end
  end
end
