module Factorix
  class CLI
    module Commands
      # Command for the info subcommand
      class Info < Dry::CLI::Command
        # Display information about the Factorio runtime environment
        desc "Display information about the Factorio runtime environment"

        # Display runtime information
        def call: (**untyped) -> void

        private

        # Display runtime information
        def display_runtime_info: (Factorix::Runtime runtime) -> void

        # Return a hash of information items
        def info_items: (Factorix::Runtime runtime) -> Hash[String, Pathname]

        # Display a single information item
        def display_item: (String label, untyped value) -> void
      end
    end
  end
end
